version: '2'

tasks:

  pr-code-checks:
    include:
      - dind
    steps:
      - name: checks-setup
        displayName: "Setup"
        include:
          - docker-socket
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
        script: |
          #!/usr/bin/env bash
          if [[ "${PIPELINE_DEBUG}" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi

          if [[ "$(get_env pipeline_namespace)" == *"pr"* ]]; then
            cd "${WORKSPACE}/$(load_repo app-repo path)"
  
            scripts/setup-test.sh
  
            NODE_VERSION="$(get_env node-version)"
            if ! command -v npm &> /dev/null ; then
              scripts/setup-code.sh --node-version "${NODE_VERSION}"
            fi
  
            npm ci
          fi

      - name: detect-secrets
        displayName: "Detect secrets"
        include:
          - docker-socket

      - name: unit-test
        displayName: "Test"
        include:
          - docker-socket
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
        script: |
          #!/usr/bin/env bash
          if [[ "${PIPELINE_DEBUG}" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi

          if [[ "$(get_env pipeline_namespace)" == *"pr"* ]]; then
            cd "${WORKSPACE}/$(load_repo app-repo path)"
            
            NODE_VERSION="$(get_env node-version)"
            if ! command -v npm &> /dev/null ; then
              scripts/setup-code.sh --node-version "${NODE_VERSION}"
            fi

            scripts/test.sh --node-version "${NODE_VERSION}" --test-suite unit
            scripts/test.sh --node-version "${NODE_VERSION}" --test-suite integration
            scripts/test.sh --node-version "${NODE_VERSION}" --test-suite regression
            scripts/test.sh --node-version "${NODE_VERSION}" --test-suite examples
          fi

      - name: compliance-checks
        displayName: "Compliance checks"
        include:
          - docker-socket

  code-checks:
    include:
      - dind
    steps:
      - name: checks-setup
        displayName: "Setup"
        include:
          - docker-socket
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
        script: |
          #!/usr/bin/env bash
          if [[ "${PIPELINE_DEBUG}" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi

      - name: detect-secrets
        displayName: "Detect secrets"
        include:
          - docker-socket

      - name: compliance-checks
        displayName: "Compliance checks"
        include:
          - docker-socket

      - name: static-scan
        displayName: "Static scan"
        include:
          - docker-socket

  code-build:
    include:
      - dind
    steps:
      - name: setup
        displayName: "Setup"
        include:
          - docker-socket
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
        script: |
          #!/usr/bin/env bash
          if [[ "${PIPELINE_DEBUG}" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi

          if [[ "$(get_env pipeline_namespace)" == *"ci"* ]]; then
            cd "${WORKSPACE}/$(load_repo app-repo path)"

            source scripts/utils.sh

            TAG="$(jq -r '.version' package.json)"

            setup-git enterprise

            git tag "${TAG}"
            git push origin tag "${TAG}"

            NODE_VERSION="$(get_env node-version)"
            if ! command -v npm &> /dev/null ; then
              scripts/setup-code.sh --node-version "${NODE_VERSION}"
            fi
  
            npm ci
          fi

      - name: unit-test
        displayName: "Test"
        include:
          - docker-socket
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
        script: |
          #!/usr/bin/env bash
          if [[ "${PIPELINE_DEBUG}" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi

          if [[ "$(get_env pipeline_namespace)" == *"ci"* ]]; then
            cd "${WORKSPACE}/$(load_repo app-repo path)"

            NODE_VERSION="$(get_env node-version)"
            if ! command -v npm &> /dev/null ; then
              scripts/setup-code.sh --node-version "${NODE_VERSION}"
            fi

            scripts/test.sh --node-version "${NODE_VERSION}" --test-suite unit
          fi

      - name: build-artifact
        displayName: "Generate documentation"
        runAfter:
          - code-checks
        include:
          - docker-socket
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
        script: |
          #!/usr/bin/env bash
          if [[ "${PIPELINE_DEBUG}" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi

          if [[ "$(get_env pipeline_namespace)" == *"ci"* ]]; then
            cd "${WORKSPACE}/$(load_repo app-repo path)"

            NODE_VERSION="$(get_env node-version)"
            if ! command -v npm &> /dev/null ; then
              scripts/setup-code.sh --node-version "${NODE_VERSION}"
            fi

            scripts/generate-docs.sh
          fi

      - name: sign-artifact
        displayName: "Sign artifacts"
        include:
          - docker-socket
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
        script: |
          #!/usr/bin/env bash
          if [[ "${PIPELINE_DEBUG}" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi

      - name: scan-artifact
        displayName: "Scan artifacts"
        include:
          - docker-socket

  deploy-checks:
    include:
      - dind
    steps:
      - name: deploy
        displayName: "Upload code to the public repository"
        runAfter:
          - code-checks
        include:
          - docker-socket
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
        script: |
          #!/usr/bin/env bash

          if [[ "$PIPELINE_DEBUG" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi

          if [[ "$(get_env pipeline_namespace)" == *"ci"* ]]; then
            cd "${WORKSPACE}/$(load_repo app-repo path)"

            scripts/sync-public-git.sh
          fi

      - name: dynamic-scan
        displayName: "Dynamic scan"
        include:
          - docker-socket

      - name: acceptance-test
        displayName: "Acceptance test"
        include:
          - docker-socket
        skip: true

  deploy-release:
    steps:
      - name: release
        displayName: "Release"
        runAfter:
          - code-checks
          - deploy-checks
        include:
          - docker-socket
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
        script: |
          #!/usr/bin/env bash
          if [[ "${PIPELINE_DEBUG}" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi

          if [[ "$(get_env pipeline_namespace)" == *"ci"* ]]; then
            cd "${WORKSPACE}/$(load_repo app-repo path)"

            NODE_VERSION="$(get_env node-version)"
            if ! command -v npm &> /dev/null ; then
              scripts/setup-code.sh --node-version "${NODE_VERSION}"
            fi

            scripts/setup-release.sh
            scripts/release.sh
          fi
